import { recommended } from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "oxlint";

export default defineConfig({
  extends: [recommended],
  options: {
    typeAware: true,
  },
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
  },
  plugins: ["unicorn", "typescript", "oxc", "vitest", "effecttsgo"],
  ignorePatterns: [
    "node_modules/**",
    ".agents/**",
    ".claude/**",
    ".alchemy/**",
    "build/**",
    "dist/**",
    "coverage/**",
    ".plans/**",
    ".reviews/**",
    ".reports/**",
    "reports/**",
    "patches/**",
    "tools/oxlint/anti-slop/**",
  ],
  jsPlugins: [
    {
      name: "anti-slop",
      specifier: "./tools/oxlint/anti-slop/index.ts",
    },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "off",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "eslint/no-await-in-loop": "off",
    "vitest/require-to-throw-message": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-control-regex": "off",
    "effecttsgo/async-function": "off",
    "effecttsgo/global-date": "off",
    "effecttsgo/node-builtin-import": "off",
    "effecttsgo/global-console-in-effect": "off",
    "effecttsgo/process-env-in-effect": "off",
    "effecttsgo/prefer-schema-over-json": "off",
    "effecttsgo/prefer-typed-schema-decoder": "off",
    "effecttsgo/unnecessary-typeof-type": "off",
    "effecttsgo/global-error-in-effect-failure": "off",
  },
});
